/** DEVELOPMENT CONTRACT SIMULATOR. Atharva replaces this entire file.
 * Decimal calculations make local UI inputs coherent; these are not the live
 * policy engine, tax jurisdiction rules, or billing guarantees. */
import { Decimal } from 'decimal.js';
import { randomUUID } from 'node:crypto';
import type { Actor, DataState, Evaluation, Line, Product, Quote, QuoteRevision } from '../contracts/application';
import type { PricedCandidate } from '../contracts/krishna';
import { requireValue } from '../server/errors';
export const dec=(n:Decimal.Value)=>new Decimal(n);
export const money=(n:Decimal.Value)=>dec(n).toDecimalPlaces(2,Decimal.ROUND_HALF_UP).toFixed(2);
export const date=()=>new Date().toISOString().slice(0,10);
export function plusPeriod(start:string, interval:string) { const d=new Date(start+'T00:00:00Z'),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+({MONTHLY:1,QUARTERLY:3,YEARLY:12}[interval]??1));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10); }
export function event(actor:Actor,text:string,revision?:string) {return {id:randomUUID(),at:new Date().toISOString(),actor:actor.name,text,revision};}
export function snapshot(q:Quote):QuoteRevision {return structuredClone({revision:q.revision,lines:q.lines,totals:q.totals,orderDiscountPct:q.orderDiscountPct,promisedDate:q.promisedDate,evaluation:q.evaluation,at:q.at});}
export function newRevision(q:Quote,actor:Actor,text:string) {requireValue(q.stage!=='CONFIRMED','Confirmed quotations are locked');q.history.push(snapshot(q));q.revision=`r${Number(q.revision.slice(1))+1}`;q.at=new Date().toISOString();q.acceptedAt=undefined;q.events.push(event(actor,text,q.revision));}
export function resolvedPrice(s:DataState,q:Quote,p:Product,variantId:string) {const c=s.customers.find(c=>c.id===q.customerId)!;const rule=s.priceRules.find(r=>r.productId===p.id&&r.tier===c.tier&&r.currency===q.currency);return money(dec(rule?.price??p.price).plus(p.variants.find(v=>v.id===variantId)?.extraPrice??0));}
export function makeLine(s:DataState,q:Quote,productId:string,variantId:string,quantity:number):Line {const p=s.products.find(p=>p.id===productId);requireValue(p?.active,'Choose an active product');requireValue(p.variants.some(v=>v.id===variantId),'Choose a valid variant');requireValue(Number.isFinite(quantity)&&quantity>0&&quantity<=1e6,'Quantity must be positive');return {id:randomUUID(),productId,variantId,description:`${p.name} · ${p.variants.find(v=>v.id===variantId)!.name}`,quantity,discountPct:0,unitPrice:resolvedPrice(s,q,p,variantId),unitCost:p.cost,taxPct:p.taxPct,tax:'0.00',net:'0.00',total:'0.00',profit:'0.00',interval:p.interval,stockTracked:p.stockTracked};}
export function reprice(s:DataState,q:Quote) {
  for(const l of q.lines){requireValue(l.quantity>0&&Number.isFinite(l.quantity),'Invalid quantity');requireValue(Number.isFinite(l.discountPct)&&l.discountPct>=0&&l.discountPct<=100,'Discount must be 0–100%');const p=s.products.find(p=>p.id===l.productId)!;l.unitPrice=resolvedPrice(s,q,p,l.variantId);l.net=money(dec(l.unitPrice).mul(l.quantity).mul(dec(1).minus(dec(l.discountPct).div(100))).mul(dec(1).minus(dec(q.orderDiscountPct).div(100))));l.tax=money(dec(l.net).mul(l.taxPct).div(100));l.total=money(dec(l.net).plus(l.tax));l.profit=money(dec(l.net).minus(dec(l.unitCost).mul(l.quantity)));}
  q.totals=Array.from(new Set(q.lines.map(l=>l.interval))).map(interval=>{const lines=q.lines.filter(l=>l.interval===interval);const sum=(key:'net'|'tax'|'total'|'profit')=>lines.reduce((a,l)=>a.plus(l[key]),dec(0));const net=sum('net'),profit=sum('profit');return {interval,net:money(net),tax:money(sum('tax')),total:money(sum('total')),profit:money(profit),marginPct:net.eq(0)?0:profit.div(net).mul(100).toDecimalPlaces(2).toNumber()};});
  const c=s.customers.find(c=>c.id===q.customerId)!;let worst=0;const reasons:string[]=[];for(const l of q.lines){const p=s.products.find(p=>p.id===l.productId)!;const ceiling=Math.min(s.policy.tierLimits[c.tier]??0,s.policy.categoryLimits[p.category]??100);const effective=dec(100).mul(dec(1).minus(dec(1).minus(dec(l.discountPct).div(100)).mul(dec(1).minus(dec(q.orderDiscountPct).div(100))))).toNumber();const excess=Math.max(0,effective-ceiling);worst=Math.max(worst,excess);if(excess>0)reasons.push(`${p.name}: ${effective.toFixed(2)}% effective discount exceeds ${ceiling}% ceiling`);}
  const chain:Evaluation['chain']=worst>0?(worst>s.policy.financeExcess?['SALES_MANAGER','FINANCE_OPS']:['SALES_MANAGER']):[];q.evaluation={status:chain.length?'PENDING':'NOT_REQUIRED',chain,step:0,reasons,worstExcess:worst};
}
export function candidatePreview(s:DataState,q:Quote,p:Product,ruleId:string):PricedCandidate {const copy=structuredClone(q);const l=makeLine(s,copy,p.id,p.variants[0].id,1);copy.lines.push(l);reprice(s,copy);const priced=copy.lines.at(-1)!;const before=q.totals.find(t=>t.interval===p.interval),after=copy.totals.find(t=>t.interval===p.interval)!;return {ruleId,productId:p.id,variantId:p.variants[0].id,name:p.name,active:p.active,compatible:true,quoteId:q.id,revision:q.revision,currency:q.currency,quantity:1,interval:p.interval,candidateMarginPct:dec(priced.net).eq(0)?-100:dec(priced.profit).div(priced.net).mul(100).toNumber(),incrementalProfit:money(dec(after.profit).minus(before?.profit??0)),marginChangePoints:before?Number((after.marginPct-before.marginPct).toFixed(2)):null};}
