import type { Actor, DataState, Quote } from '../contracts/application';
import { makeLine,reprice,date,plusPeriod } from './pricing';
// Demo credentials for the development fixture store; one distinct password
// per account. Production accounts always use their own signup credentials.
export const userPasswords:Record<string,string>={
  'admin-dev':'admin-dealflow-2026!',
  'rep-arjun':'arjun-dealflow-2026!',
  'manager-sana':'sana-dealflow-2026!',
  'finance-farah':'farah-dealflow-2026!',
  'customer-neha':'neha-dealflow-2026!',
  'customer-beta-user':'riya-dealflow-2026!',
  'customer-gamma-user':'meera-dealflow-2026!',
};
export function seed():DataState {
  const users:Actor[]=[['admin-dev','Dev Mehta','admin','ADMIN'],['rep-arjun','Arjun Shah','sales','SALES_REP'],['manager-sana','Sana Iyer','manager','SALES_MANAGER'],['finance-farah','Farah Khan','finance','FINANCE_OPS'],['customer-neha','Neha Kapoor','acme','CUSTOMER'],['customer-beta-user','Riya Patel','beta','CUSTOMER'],['customer-gamma-user','Meera Joshi','gamma','CUSTOMER']].map(([id,name,email,role])=>({id,name,email:`${email}@dealflow.test`,role:role as Actor['role'],active:true,...(email==='acme'?{customerId:'customer-acme'}:email==='beta'?{customerId:'customer-beta'}:email==='gamma'?{customerId:'customer-north'}:{})}));
  const products:DataState['products']=[['laptop','Latitude Pro 14','Hardware','50000','40000','ONE_TIME',true],['dock','Connect USB-C Dock','Hardware','3000','2000','ONE_TIME',true],['mouse','Precision Mouse','Hardware','1800','900','ONE_TIME',true],['support','Business Care','Services','1000','400','MONTHLY',false],['setup','Workspace Setup','Services','5000','1800','ONE_TIME',false],['monitor','Studio Display 27','Hardware','18000','14000','ONE_TIME',true]].map(([id,name,category,price,cost,interval,stockTracked])=>({id:String(id),name:String(name),category:String(category),price:String(price),cost:String(cost),interval:interval as 'ONE_TIME'|'MONTHLY',stockTracked:!!stockTracked,description:`${name} for modern teams.`,unit:interval==='MONTHLY'?'seat':'unit',taxPct:18,active:true,planId:interval==='MONTHLY'?'plan-care':'',variants:[{id:`${id}-standard`,name:'Standard',extraPrice:'0.00'},...(id==='laptop'?[{id:'laptop-32gb',name:'32 GB / 1 TB',extraPrice:'8000.00'}]:[])]}));
  const s:DataState={users,products,customers:[{id:'customer-acme',name:'Acme Studio',email:'neha@acme.test',tier:'Gold',currency:'INR',repId:'rep-arjun'},{id:'customer-beta',name:'Beta Industries',email:'riya@beta.test',tier:'Silver',currency:'INR',repId:'rep-arjun'},{id:'customer-north',name:'Northstar Labs',email:'ops@northstar.test',tier:'Bronze',currency:'INR',repId:'rep-arjun'}],priceRules:[{id:'price-gold-dock',productId:'dock',tier:'Gold',currency:'INR',price:'2800.00'}],quotes:[],orders:[],warehouses:[{id:'warehouse-main',name:'Main warehouse',shippingCost:'600.00',active:true},{id:'warehouse-east',name:'East depot',shippingCost:'850.00',active:true}],stock:[],plans:[{id:'plan-care',name:'Business Care Monthly',interval:'MONTHLY',price:'1000.00',prorate:true,cancellation:'IMMEDIATE_CREDIT'},{id:'plan-premium',name:'Priority Care Monthly',interval:'MONTHLY',price:'1600.00',prorate:true,cancellation:'PERIOD_END'}],subscriptions:[],invoices:[],payments:[],rules:[{id:'rule-dock',baseProductId:'laptop',candidateProductId:'dock',coPurchaseScore:90,promotionLabel:'Team essential',minimumMarginPct:20,active:true},{id:'rule-mouse',baseProductId:'laptop',candidateProductId:'mouse',coPurchaseScore:75,promotionLabel:null,minimumMarginPct:20,active:true},{id:'rule-care',baseProductId:'laptop',candidateProductId:'support',coPurchaseScore:60,promotionLabel:null,minimumMarginPct:25,active:true},{id:'rule-fallback',baseProductId:null,candidateProductId:'monitor',coPurchaseScore:5,promotionLabel:'Workspace upgrade',minimumMarginPct:30,active:true}],proposals:[],messages:[],policy:{tierLimits:{Bronze:5,Silver:10,Gold:15},categoryLimits:{Hardware:15,Services:10},financeExcess:5,financeWeighted:3,budget:'50000.00'},healthSettings:{stalledDays:5,anomalyPoints:10,minimumHistory:3},flags:[],tasks:[]};
  for(const p of products.filter(p=>p.stockTracked))for(const w of s.warehouses)s.stock.push({id:`stock-${p.id}-${w.id}`,warehouseId:w.id,variantId:p.variants[0].id,onHand:p.id==='laptop'?(w.id==='warehouse-main'?6:3):p.id==='dock'?10:20,reserved:0,threshold:5});
  for(let i=0;i<6;i++){const q:Quote={id:`Q-${1042+i}`,name:['Studio expansion','Hybrid workspace','Support renewal','New design team','Hardware refresh','Engineering rollout'][i],customerId:i===2?'customer-beta':i===4?'customer-north':'customer-acme',repId:'rep-arjun',currency:'INR',revision:'r1',stage:i===0?'SENT':i===1?'PENDING_APPROVAL':'DRAFT',sent:i<3,orderDiscountPct:0,promisedDate:null,evaluation:{status:'NOT_REQUIRED',chain:[],step:0,reasons:[],worstExcess:0},lines:[],totals:[],at:new Date(Date.now()-i*86400000*2).toISOString(),history:[],events:[],requestedDate:null,dateReviewPending:false};q.lines=[makeLine(s,q,'laptop','laptop-standard',i===0?10:2+i),makeLine(s,q,'support','support-standard',i===0?10:2+i)];q.lines[0].discountPct=i===1?18:12;q.lines[1].discountPct=i===1?16:8;reprice(s,q);q.events.push({id:`event-${i}`,actor:'Arjun Shah',at:q.at,text:'Quotation created',revision:'r1'});s.quotes.push(q);}
  const source=s.quotes[5];const order={id:'O-1001',quoteId:source.id,revision:source.revision,customerId:source.customerId,currency:'INR',lines:structuredClone(source.lines),totals:structuredClone(source.totals),status:'PENDING',promisedDate:date(),allocations:[],backorders:[],events:[]};s.orders.push(order);source.stage='CONFIRMED';source.sent=true;source.orderId=order.id;source.evaluation.status='APPROVED';
  const t=order.totals.find(t=>t.interval==='ONE_TIME')!;s.invoices.push({id:'INV-1001',orderId:order.id,customerId:order.customerId,currency:'INR',dueDate:plusPeriod(date(),'MONTHLY'),lines:order.lines.filter(l=>l.interval==='ONE_TIME').map(l=>({id:l.id,description:l.description,quantity:l.quantity,unitPrice:l.unitPrice,discountPct:l.discountPct,net:l.net,tax:l.tax,total:l.total})),net:t.net,tax:t.tax,total:t.total,paid:'0.00',credited:'0.00',outstanding:t.total,status:'UNPAID',events:[]});s.subscriptions.push({id:'SUB-1001',orderId:order.id,customerId:order.customerId,productId:'support',planId:'plan-care',quantity:7,unitPrice:'920.00',status:'ACTIVE',periodStart:date(),periodEnd:plusPeriod(date(),'MONTHLY'),nextBill:date(),events:[]});s.flags.push({id:'flag-stalled',quoteId:'Q-1045',type:'STALLED',reason:'No meaningful activity for 6 days',status:'OPEN',detectedAt:new Date().toISOString()});return s;
}
