'use client';
import {useState} from 'react';
import {forms,type Field} from '../../contracts/forms';
import {Button,Input,Select,Link,StatusBadge,Money,Heading,Section,Table,FormAction,Fields,api,newId,type Context} from './shared';
import {IntegrationsPanel} from './IntegrationsPanel';
export default function Setup({ctx}:{ctx:Context}){const {d,actor,path,run,reload}=ctx,[search,setSearch]=useState(''),[error,setError]=useState('');const tab=path.startsWith('/products')?'products':path==='/price-lists'?'priceRules':path==='/policies'?'policies':path.split('/')[2]??'customers';const canEdit=actor.role==='ADMIN'||(actor.role==='SALES_MANAGER'&&['policies','recommendations','health'].includes(tab))||(actor.role==='FINANCE_OPS'&&['plans','warehouses'].includes(tab));
 const collection=tab==='warehouses'?'warehouses':tab,form=forms[collection],records=(d[collection as 'customers']??[]) as unknown as Record<string,unknown>[];
 const tabs=[['customers','Customers'],['users','Users & roles'],['warehouses','Warehouses & stock'],['plans','Subscription policies'],['recommendations','Recommendations'],['health','Health settings']];
 return <><Heading title={tab==='products'?'Product catalog':tab==='priceRules'?'Customer price lists':tab==='policies'?'Discount & approval policy':tabs.find(t=>t[0]===tab)?.[1]??'Setup'} description="Shared configuration, used by the connected service on subsequent operations."/><div className="tabs">{tab==='products'||tab==='priceRules'?<><Link href="/products" className={tab==='products'?'selected':''}>Products & variants</Link><Link href="/price-lists" className={tab==='priceRules'?'selected':''}>Price lists</Link></>:<>{tabs.map(([t,n])=><Link href={'/settings/'+t} key={t} className={t===tab?'selected':''}>{n}</Link>)}<Link href="/policies" className={tab==='policies'?'selected':''}>Approval policy</Link></>}</div>{error&&<p className="error" role="alert">{error}</p>}
 {form&&<><div className="filters"><Input label="Search configuration" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find by name, email or reference…"/>{canEdit&&tab!=='users'&&<FormAction title={'Create '+form.title.toLowerCase()} fields={form.fields} d={d} initial={Object.fromEntries(form.fields.map(f=>[f.key,f.type==='checkbox'?true:f.options?.[0]??(f.type==='number'?0:'')]))} onSubmit={v=>run('saveRecord',{requestKey:v.requestKey,collection,record:v})}/>}</div><Section title={form.title+' records'}><Table head={[...form.fields.slice(0,6).map(f=>f.label),'Actions']} rows={records.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map(r=>[...form.fields.slice(0,6).map(f=>{const value=r[f.key];if(f.key==='name'&&tab==='products')return <Link href={'/products/'+r.id}>{String(value)}</Link>;if(typeof value==='boolean')return <StatusBadge status={value?'ACTIVE':'INACTIVE'}/>;if(['price','cost','shippingCost'].includes(f.key))return <Money amount={String(value)} currency="INR"/>;if(f.source){const source=f.source==='reps'?d.users:d[f.source as 'products'];return source?.find(x=>x.id===value)?.name??String(value??'—');}return String(value??'—');}),canEdit?<FormAction title={'Edit '+form.title.toLowerCase()} fields={form.fields} initial={r} d={d} onSubmit={v=>run('saveRecord',{requestKey:v.requestKey,id:r.id,collection,record:v})}/>:<span className="muted">View only</span>])}/></Section></>}
 {tab==='products'&&d.products.filter(p=>path.split('/')[2]?p.id===path.split('/')[2]:true).map(p=><Section title={p.name+' · variants'} key={p.id} actions={canEdit?<FormAction title="Add variant" fields={[{key:'text',label:'Variant / attribute combination',required:true},{key:'extraPrice',label:'Extra price',type:'number',min:0,required:true}]} initial={{extraPrice:0}} onSubmit={v=>run('variant',{...v,id:p.id})}/>:undefined}><Table head={['Variant','Extra price','Stock tracked','Status']} rows={p.variants.map(v=>[v.name,<Money amount={v.extraPrice} currency="INR"/>,p.stockTracked?'Yes':'No',<StatusBadge status={p.active?'ACTIVE':'INACTIVE'}/>])}/></Section>)}
 {tab==='warehouses'&&<Section title="Stock & replenishment" actions={canEdit?<FormAction title="Receive stock" d={d} fields={[{key:'warehouseId',label:'Warehouse',type:'select',source:'warehouses',required:true},{key:'variantId',label:'Physical variant',type:'select',options:d.products.filter(p=>p.stockTracked).flatMap(p=>p.variants.map(v=>v.id)),required:true},{key:'quantity',label:'Received quantity',type:'number',min:1,required:true}]} onSubmit={v=>run('stockReceipt',v)}/>:undefined}><Table head={['Product / variant','Warehouse','On hand','Reserved','Available','Threshold','Action']} rows={d.stock.map(s=>{const p=d.products.find(p=>p.variants.some(v=>v.id===s.variantId));return [p?.name+' / '+p?.variants.find(v=>v.id===s.variantId)?.name,d.warehouses.find(w=>w.id===s.warehouseId)?.name,s.onHand,s.reserved,s.onHand-s.reserved,<>{s.threshold} {s.onHand-s.reserved<=s.threshold&&<StatusBadge status="PENDING_APPROVAL" label="Replenish"/>}</>,canEdit?<FormAction title="Set replenishment threshold" fields={[{key:'threshold',label:'Minimum available quantity',type:'number',min:0,required:true}]} initial={{threshold:s.threshold}} onSubmit={v=>run('stockThreshold',{...v,id:s.id})}/>:null];})}/></Section>}
 {tab==='policies'&&<Policy ctx={ctx} editable={canEdit}/>}
 {tab==='health'&&<Section title="Detection thresholds"><FormAction title={canEdit?'Edit health settings':'View health settings'} fields={[{key:'stalledDays',label:'Stalled after days',type:'number',min:1,required:true},{key:'anomalyPoints',label:'Margin anomaly threshold (percentage points)',type:'number',min:0,required:true},{key:'minimumHistory',label:'Minimum comparable history',type:'number',min:1,required:true}]} initial={{...d.healthSettings}} onSubmit={v=>run('healthSettings',{requestKey:v.requestKey,settings:v})}/><dl>{Object.entries(d.healthSettings).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></Section>}
 {tab==='recommendations'&&<Section title="Pairings, promotions & fallback rules" actions={canEdit?<RuleForm ctx={ctx}/>:undefined}><Table head={['Base product','Suggested product','Promotion','Score','Minimum margin','Active','Actions']} rows={d.rules.map(r=>[d.products.find(p=>p.id===r.baseProductId)?.name??'Fallback (all quotes)',d.products.find(p=>p.id===r.candidateProductId)?.name,r.promotionLabel??'—',r.coPurchaseScore,r.minimumMarginPct+'%',r.active?'Yes':'No',canEdit?<><RuleForm ctx={ctx} rule={r}/><FormAction title="Delete recommendation rule" danger onSubmit={async()=>{await api('recommendations/rules',{rules:d.rules.filter(x=>x.id!==r.id)});await reload();}}/></>:null])}/></Section>}
 {tab==='users'&&<p className="hint">New users request access through signup. An administrator verifies identity and assigns a role and customer association before activation.</p>}
 {actor.role==='ADMIN'&&<IntegrationsPanel/>}
 {actor.role==='ADMIN'&&<Section title="Development workspace"><p>Development fixture changes survive page reload and server restart in the local JSON store. Reset restores the supplied scenario and development accounts.</p><FormAction title="Reset development fixture" danger description="This resets development business records and accounts. It does not access a shared database." onSubmit={v=>run('reset',v)}/></Section>}</>;
}
function RuleForm({ctx,rule}:{ctx:Context;rule?:Context['d']['rules'][number]}){const {d,reload}=ctx;return <FormAction title={rule?'Edit rule':'Add recommendation rule'} d={d} initial={rule?{...rule,baseProductId:rule.baseProductId??'',promotionLabel:rule.promotionLabel??''}:{baseProductId:'',coPurchaseScore:0,minimumMarginPct:20,active:true,promotionLabel:''}} fields={[{key:'baseProductId',label:'Base product (blank for fallback)',type:'select',source:'products'},{key:'candidateProductId',label:'Suggested product',type:'select',source:'products',required:true},{key:'promotionLabel',label:'Promotion label'},{key:'coPurchaseScore',label:'Co-purchase ranking score',type:'number',min:0,required:true},{key:'minimumMarginPct',label:'Minimum candidate margin (%)',type:'number',min:0,max:100,required:true},{key:'active',label:'Active',type:'checkbox'}]} onSubmit={async v=>{const next={id:rule?.id??newId(),baseProductId:String(v.baseProductId)||null,candidateProductId:String(v.candidateProductId),promotionLabel:String(v.promotionLabel)||null,coPurchaseScore:Number(v.coPurchaseScore),minimumMarginPct:Number(v.minimumMarginPct),active:v.active===true};await api('recommendations/rules',{rules:[...d.rules.filter(r=>r.id!==rule?.id),next]});await reload();}}/>;}
function Policy({ctx,editable}:{ctx:Context;editable:boolean}){const {d,run}=ctx,[value,set]=useState<Record<string,unknown>>({...d.policy.tierLimits,...d.policy.categoryLimits,financeExcess:d.policy.financeExcess,financeWeighted:d.policy.financeWeighted,budget:d.policy.budget}),[error,setError]=useState('');const fields:Field[]=[...Object.keys(d.policy.tierLimits),...Object.keys(d.policy.categoryLimits)].map(key=>({key,label:key+' discount limit (%)',type:'number',min:0,max:100,required:true}));fields.push({key:'financeExcess',label:'Finance worst-line excess (points)',type:'number',min:0,max:100,required:true},{key:'financeWeighted',label:'Finance weighted excess (points)',type:'number',min:0,max:100,required:true},{key:'budget',label:'Discount budget (INR)',type:'number',min:0,required:true});return <Section title="Discount limits and sequential routing"><p>Effective limits use both customer tier and category. Manager review precedes Finance when risk thresholds are exceeded.</p><form onSubmit={async e=>{e.preventDefault();try{await run('policy',{policy:{tierLimits:Object.fromEntries(Object.keys(d.policy.tierLimits).map(k=>[k,Number(value[k])])),categoryLimits:Object.fromEntries(Object.keys(d.policy.categoryLimits).map(k=>[k,Number(value[k])])),financeExcess:Number(value.financeExcess),financeWeighted:Number(value.financeWeighted),budget:String(value.budget)}});setError('');}catch(e){setError((e as Error).message);}}}><fieldset disabled={!editable}><Fields fields={fields} value={value} set={set}/>{error&&<p className="error" role="alert">{error}</p>}<Button type="submit">Save policy</Button></fieldset></form></Section>;}
