export interface Field { key:string;label:string;type?:'text'|'number'|'date'|'email'|'select'|'textarea'|'checkbox';required?:boolean;options?:string[];source?:string;min?:number;max?:number }
export const forms:Record<string,{title:string;fields:Field[]}>={
  customers:{title:'Customer',fields:[{key:'name',label:'Company name',required:true},{key:'email',label:'Contact email',type:'email',required:true},{key:'tier',label:'Customer tier',type:'select',options:['Bronze','Silver','Gold'],required:true},{key:'currency',label:'Currency',type:'select',options:['INR'],required:true},{key:'repId',label:'Responsible sales rep',type:'select',source:'reps',required:true}]},
  products:{title:'Product',fields:[{key:'name',label:'Product name',required:true},{key:'category',label:'Category',type:'select',options:['Hardware','Services'],required:true},{key:'unit',label:'Unit of measure',required:true},{key:'description',label:'Description',type:'textarea'},{key:'price',label:'Base price (INR)',type:'number',min:0,required:true},{key:'cost',label:'Unit cost (INR)',type:'number',min:0,required:true},{key:'taxPct',label:'Tax (%)',type:'number',min:0,max:100,required:true},{key:'interval',label:'Billing frequency',type:'select',options:['ONE_TIME','MONTHLY','QUARTERLY','YEARLY'],required:true},{key:'planId',label:'Subscription plan',type:'select',source:'plans'},{key:'stockTracked',label:'Track physical stock',type:'checkbox'},{key:'active',label:'Active product',type:'checkbox'}]},
  priceRules:{title:'Customer price',fields:[{key:'productId',label:'Product',type:'select',source:'products',required:true},{key:'tier',label:'Tier',type:'select',options:['Bronze','Silver','Gold'],required:true},{key:'currency',label:'Currency',type:'select',options:['INR'],required:true},{key:'price',label:'Customer price',type:'number',min:0,required:true}]},
  warehouses:{title:'Warehouse',fields:[{key:'name',label:'Warehouse name',required:true},{key:'shippingCost',label:'Estimated shipment cost',type:'number',min:0,required:true},{key:'active',label:'Available for allocation',type:'checkbox'}]},
  plans:{title:'Subscription plan',fields:[{key:'name',label:'Plan name',required:true},{key:'interval',label:'Frequency',type:'select',options:['MONTHLY','QUARTERLY','YEARLY'],required:true},{key:'price',label:'Price per unit',type:'number',min:0,required:true},{key:'prorate',label:'Prorate mid-period changes',type:'checkbox'},{key:'cancellation',label:'Cancellation policy',type:'select',options:['IMMEDIATE_CREDIT','PERIOD_END'],required:true}]},
  users:{title:'User access',fields:[{key:'name',label:'Name',required:true},{key:'email',label:'Email',type:'email',required:true},{key:'role',label:'Assigned role',type:'select',options:['SALES_REP','SALES_MANAGER','FINANCE_OPS','ADMIN','CUSTOMER'],required:true},{key:'customerId',label:'Verified customer association',type:'select',source:'customers'},{key:'active',label:'Active account',type:'checkbox'}]},
};
